### PR TITLE
Some improvements

### LINKED ISSUE #477: Tests don't run
**Describe the bug**
Tests get discovered but just not running

**To Reproduce**
It works initially and after some time it stop working.

**Expected behavior**
Tests should run.

**Screenshots**
Screen Shot 2563-11-30 at 14 27 50
Screen Shot 2563-11-30 at 14 28 06

**Desktop (please complete the following information):**
 - OS: [macOS Catalina]
 - Playwright version [1.6.2]
 - jest-playwright version [1.4.1]

**Jest configuration (`jest.e2e.config.js`):**

 ```js
module.exports = {
  verbose: true,
  collectCoverage: false,
  preset: 'jest-playwright-preset',
  testMatch: ['<rootDir>/src/**/*.test.e2e.js'],
}
```

`jest-playwright.config.js`:
```js
module.exports = {
  collectCoverage: false,
  browsers: ['chromium', 'webkit'],
  launchOptions: {
    headless: !process.env.DEBUG,
  },
  useDefaultBrowserType: true,
}
```

Simple test file `playwright.test.e2e.js`
```js
test('test', async () => {
  await page.goto('http://localhost:3000/')

  await jestPlaywright.debug()
})
```

**Additional context**
I tried clear jest cache and run with `--no-cache`, tried remove `yarn.lock` and `node_modules`.
After it stopped can't make it work again.

Trying to run like this
`DEBUG=true npx jest -c jest.e2e.config.js` or `npx jest -c jest.e2e.config.js`

Main jest config
```js
module.exports = {
  verbose: true,
  collectCoverage: true,
  collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}'],
  coverageReporters: ['text', 'html'],
  coverageDirectory: './coverage/',
  coveragePathIgnorePatterns: [
    'spec.js',
    'polyfills',
    'service-worker',
    'coverage',
    'cypress',
    'cypress-coverage',
  ],
  testMatch: ['<rootDir>/src/**/*.test.js'],
  transform: { '\\.js': ['babel-jest'] },
}
```

### PR DESCRIPTION
**Pull request by mmarkelov**
close #477

### CODE REVIEW

File: types/global.d.ts [hunk 1]
```diff
@@ -132,6 +132,8 @@ declare global {
     }
     interface Describe {
       jestPlaywrightSkip: JestParams<SkipOption>
+      jestPlaywrightDebug: JestPlaywrightTestDebug
+      jestPlaywrightConfig: JestPlaywrightTestConfig
```
Comment (kenny-f) [inline types/global.d.ts:136]: @mmarkelov is this correct? 
in https://github.com/playwright-community/jest-playwright/blob/master/src/extends.ts#L104 
I don't see describe being extended with `jestPlaywrightDebug` or `jestPlaywrightConfig`. Only `jestPlaywrightSkip`. 
Or am I missing something?

Comment (mmarkelov) [reply types/global.d.ts:136]: @kenny-f my bad. I'll think about if we need these kind of helpers for `describe` or we just want to **skip** only

Comment (kenny-f) [reply types/global.d.ts:136]: @mmarkelov I think it's useful to have for `describe` as well as it allows people to group tests differently and not be restricted by what is extended and what isn't.
