### PR TITLE
Fix selectors registration

### LINKED ISSUE #99: Error when using custom Jest runner with selector engine: "shadow" selector engine has been already registered
**UPDATED**

Getting an error when using custom Jest runner with selector engine: `"shadow" selector engine has been already registered`. See repro in comments below.

**Original problem below. After update, solved by upgrading also Playwright.**

~~Just upgraded to latest jest-playwright (0.1.1) and get this when running:~~
 
```sh
FAIL   E2E  tests/e2e/suite/login/login.e2e.test.js
  ● Test suite failed to run

    Cannot evaluate a string with arguments

      at assert (../../node_modules/playwright-core/lib/helper.js:196:15)
      at Function.evaluationString (../../node_modules/playwright-core/lib/helper.js:25:13)
      at Selectors.register (../../node_modules/playwright-core/lib/selectors.js:31:40)
      at Selectors.<anonymous> (../../node_modules/playwright-core/lib/helper.js:55:31)
      at ../../node_modules/jest-playwright-preset/lib/utils.js:69:88
          at Array.map (<anonymous>)
      at Object.exports.getPlaywrightInstance (../../node_modules/jest-playwright-preset/lib/utils.js:69:41)
      at PlaywrightEnvironment.setup (../../node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:75:36)
```

~~My jest-playwright.config.js:~~

```javascript
const {
  selectorEngine,
} = require('query-selector-shadow-dom/plugins/playwright');

module.exports = {
  selectors: [{ name: 'shadow', script: selectorEngine }],
  server: {
    command: 'npm run start',
  },
};
```

### PR DESCRIPTION
**Pull request by mmarkelov**
Hack to fix #99

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -89,9 +89,11 @@ export const getPlaywrightInstance = async (
     const playwright = require('playwright')
     if (selectors) {
       await Promise.all(
-        selectors.map(({ name, script }) =>
-          playwright.selectors.register(name, script),
-        ),
+        selectors.map(({ name, script }) => {
+          if (!playwright.selectors._engines.get(name)) {
```
Comment (mxschmitt) [inline src/utils.ts:93]: seems like a weird workaround to access a private field. hmm

Comment (mmarkelov) [reply src/utils.ts:93]: Of cause this is true, but for now I can't see any others solutions to fix it. https://github.com/playwright-community/jest-playwright/issues/99#issuecomment-609698736
