### PR TITLE
Fix rootDir for tests

### LINKED ISSUE #120: Searching the wrong directory for config when using Jest `projects` option
My directory structure looks like this:

```
tests/
  visual-tests/
    jest.config.js
    jest-playwright.config.js
  other-tests/
    jest.config.js
  jest.config.js
```

The outermost Jest config uses the `projects` field to run other Jest projects.  Each project uses its own config file, and `<rootDir>` replacement refers to the folder containing the Jest config specific to that project.

The inner Jest config in `visual-tests` is the one that uses the `jest-playwright-preset`.

Expected behavior:
The runner looks for `jest-playwright.config.js` in `tests/visual-tests/`
Actual behavior:
The runner looks for the file in `tests` and returns the default config.

Note:
When the test actually run, it uses the correct launch options.  So it's looking in the wrong place when getting a list of browsers and devices, but later looks in the correct place for the launch and context options.

### PR DESCRIPTION
**Pull request by mmarkelov**
Close #120

### CODE REVIEW

File: src/constants.ts [hunk 1]
```diff
@@ -13,3 +13,5 @@ export const DEFAULT_CONFIG: Config = {
   devices: [],
   exitOnPageError: true,
 }
+
+export const DEFAULT_TEST_PLAYWRIGHT_TIMEOUT = 15000
```
Comment (mxschmitt) [inline src/constants.ts:17]: maybe we should make this configurable. Because when e.g. a selector code not be found -> TimeoutError then Jest wont make a nice error reporting. Because Jest timeout < Playwright timeout.

Comment (mmarkelov) [reply src/constants.ts:17]: @mxschmitt sounds good. I should think how we can configure this.

Comment (mmarkelov) [reply src/constants.ts:17]: @mxschmitt you can configure it in **jest config** with **testTimeout**. I think that it's enought for a while
